### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by dharz20** [isage/septerra-core-vita#1]
crashing sometimes when i go to town or leaving, infinite loop saying dialogues and also  i can't control the 3rd party when im in combat

**Comment by isage** [comment]
Can you elaborate on "dialogues loop"?
You should be able to switch between party members in battle with mouse or square/triangle/circle

**Comment by dharz20** [comment]
> Can you elaborate on "dialogues loop"? You should be able to switch between party members in battle with mouse or square/triangle/circle

always repeating there dialogues sample "hey maya" they will repeat this infinite times i never get the chances to finish there conversation and also the circle button doesnt work on 3rd character in battle the only way i can control him/her in battle is by touching his icon on touchscreen

**Comment by isage** [comment]
Should be fixed with latest release.
