### ISSUE TITLE
DB files probably should be created and QuickTime issues

### ISSUE THREAD

**Issue by PookaMustard** [isage/septerra-core-vita#2]
When seeing this port mentioned on Reddit, I grabbed my Septerra Core files to use them with it. But there was one problem: I had the steam version and not the GOG one, so I had to do the extra steps for transcoding the movies and followed the instructions as written. This would end with the splash screen showing up, a brief black screen and the Vita exiting the game.

After much tinkering and looking at files of people who got it working, I saw the DB files were present but as zero byte files. When I added them, I got the game to work. (The instructions says the DB files should not be copied). So maybe the DB files need to be created as 0 bytes automatically on startup? If not, then mentioned in the instructions?

The next ordeal is the movies. My non-GOG version had a QT7 installer so I installed it and applied the sc_patch. The movies are white screen with the audio playing. I hunted down the internet for QT4.1.2 and QT4.0, both versions gave me transcoded AVI files different than what QT7 produced, but it was still white screen with audio.

I didn't get past the title screen but at least it works.

Thanks for getting Septerra Core and adding another port to the Vita.

**Comment by isage** [comment]
Hm. The code should check if db files are absent (or zero size) and use avi. I'll take a look at why presence check fails.
As for transcoding: sadly, I don't know what flags Timesleep uses. I've tried transcoding with ffmpeg, but files were waaaay bigger

**Comment by PookaMustard** [comment]
> As for transcoding: sadly, I don't know what flags Timesleep uses. I've tried transcoding with ffmpeg, but files were waaaay bigger

Can you at least share if I need to hunt down any specific QT4.X installer? Eliminating this uncertainty could be a step forward. There's a bunch of compatible avi files in circulating copies of the game but I'm also unsure how they were transcoded in the first place. Possibly the GOG AVI files? Actually I should check gogdb.

EDIT: yes, [so these AVI files are transcoded by GOG](https://www.gogdb.org/manifest/4422cf27-669f-48de-ac3f-c99217e1008c). They're different from my QT7 and QT4 results too.

**Comment by isage** [comment]
I've used qt 4 bundled with original pc release and that worked. Problem is, it's installer seems to be bundled with cd's autorun. I'll take a look if i can separate and share it.

**Comment by isage** [comment]
Hm. Well, it looks like i lied. Applying Timeslip patch over original CD release produces white-screen files.
Also, i've noticed that GOG version of cutscenes (avi ones) have lower quality than original ones.
Sadly, vita ffmpeg port can't read .DB videos (and if i enable support for codec it crashes after a few frames).
I'm playing around with transcoding .DB to .avi with ffmpeg with acceptable results.

**Comment by isage** [comment]
I've added (well, fixed) support for original DB files. No converting needed anymore.

**Comment by PookaMustard** [comment]
I'll try the latest version after getting back home where the Vita is and write up on any further issues. Thanks! ~~On second thought I should've just bought the game on GOG when I got the chance, but this port should hopefully be the next best thing.~~

**Comment by PookaMustard** [comment]
Alright, good news. It just works. None of that installing quicktime and transcoding stuff, it's just drag and drop the game data. Should work for both non-GOG and GOG if the game's file manifest on gogdb is any indicator.

These are the files I copied over. (PDF and txt obviously not necessary for running the game but they're nice to have)

```anim.db
level.db
M1.DB
M2.DB
M3.DB
M4.DB
M5.DB
M6.DB
M7.DB
M8.DB
M9A.DB
M9B.DB
Manual.pdf
MONOLITH.DB
readme.txt
septerra.db
septerra.exe
septerra.idx
septerra.ini
septerra.mft
sound.db
text.db
topware.db
valkyrie.db
```

Thanks for the update and thanks again for the port!
